### ISSUE TITLE
Move to latest 0.6 http4s

### ISSUE THREAD

**Issue by ppurang** [ppurang/httpize#7]
@bryce-anderson  We are still on 0.3.0 would it be possible for you to take some time out and upgrade us? Thanks :)

**Comment by bryce-anderson** [comment]
Do you mind if I wait until the very soon 0.6.0 release?

**Comment by ppurang** [comment]
Sure.. Even Better.

**Comment by ppurang** [comment]
Thanks for taking the time out. Already running on httpize.heroku.com.
